import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
await page.goto('https://www.landydev.com/#/auth/login');
await page.getByRole('textbox', { name: 'Email' }).click();
await page.getByRole('textbox', { name: 'Email' }).fill('velmurugan@stepladdersolutions.com');
await page.getByRole('textbox', { name: 'Password' }).click();
await page.getByRole('textbox', { name: 'Password' }).fill('Test@123');
await page.getByRole('button', { name: 'Login' }).click();
await page.goto('https://www.landydev.com/#/pages/riskPolicySearch');
await page.getByRole('button', { name: '   New Application' }).click();
await page.getByLabel('State').selectOption('AL');
await page.locator('#state').nth(1).selectOption('REEXP');
await page.getByRole('textbox', { name: 'Pick a producer' }).click();
await page.getByRole('textbox', { name: 'Pick a producer' }).fill('HHL01-A,  Herbert H. Landy Insurance Agency, Inc.,  Norwood,  MA,  02062-5041').clicl();

await page.getByRole('textbox', { name: 'Search Firm Name' }).click();
await page.getByRole('textbox', { name: 'Search Firm Name' }).fill('REEXP Test1');
await page.locator('nb-layout-column').click();
await page.getByRole('textbox', { name: 'Sizing example input' }).first().click();
await page.getByRole('textbox', { name: 'Sizing example input' }).first().fill('alabama');
await page.getByText('Alabama A&M University').click();
await page.locator('input[name="effDate2"]').fill('2026-01-10');
await page.getByLabel('Retroactive Date ---Choose an').selectOption('1: true');
await page.getByRole('button', { name: 'save & Close' }).click();
await page.locator('nb-accordion-item-header').filter({ hasText: 'Application Details' }).click();
await page.locator('select[name="typeOfFirmReId"]').selectOption('1');
await page.getByRole('textbox', { name: 'Professionals Earning > 20k' }).click();
await page.getByRole('textbox', { name: 'Professionals Earning > 20k' }).fill('12');
await page.getByPlaceholder('Annual # TransactionSides').click();
await page.getByPlaceholder('Annual # TransactionSides').fill('12');
await page.getByRole('textbox', { name: '$' }).click();
await page.getByRole('textbox', { name: '$' }).press('ArrowLeft');
await page.getByRole('textbox', { name: '$' }).press('ArrowLeft');
await page.getByRole('textbox', { name: '$' }).press('ArrowLeft');
await page.getByRole('button', { name: 'save & Close' }).click();
await page.getByRole('button', { name: ' Next' }).click();
await page.getByText('$ 597').nth(1).click();
await page.getByRole('button', { name: 'Proceed' }).click();
await page.getByRole('button', { name: 'Accounting' }).click();
await page.getByRole('link', { name: 'Payment', exact: true }).click();
await page.locator('#paymentReceived3').click();
await page.locator('#paymentReceived3').press('ArrowLeft');
await page.locator('#paymentReceived3').press('ArrowLeft');
await page.locator('#paymentReceived3').press('ArrowLeft');
await page.locator('#checkNumber').click();
await page.locator('#checkNumber').fill('258369');
await page.getByRole('button', { name: 'Autofill  ($597.00)' }).click();
await page.getByRole('button', { name: 'Save  & Issue' }).click();
await page.getByRole('button', { name: 'Okay' }).click();
await page.getByRole('link', { name: 'Accounting' }).click();
await page.getByRole('link', { name: 'Policy Queued' }).click();
await page.locator('.ng2-smart-actions').first().click();
await page.getByRole('button', { name: 'Issue Policy' }).click();
await page.getByRole('button', { name: 'Yes' }).click();
await page.getByRole('link', { name: 'Underwriting' }).click();
await page.getByText('REEXP Test1').click();
});